College-Corner/Cart_and_Checkout/urls.py
from django.urls import path
from . import views

app_name = 'Cart'

urlpatterns = [
    path('', views.cartcalling, name="cartlist"),

]

College-Corner/CollegeCorner/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('cart/',include('Cart_and_Checkout.urls')),
    path('ourproducts/',include('Product_Catalog.urls')),
    path('about/', views.about),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

College-Corner/Product_Catalog/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'Product_Catalog'

urlpatterns = [
    path('', login_required(views.product_list.as_view()), name='ProductList'),
]

College-Corner/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]
    

College-Corner/Cart_and_Checkout/models.py
from django.db import models

# Create your models here.

College-Corner/Product_Catalog/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return self.name

College-Corner/accounts/models.py
from django.db import models

# Create your models here.

College-Corner/order_management/models.py
from django.db import models

# Create your models here.

College-Corner/payment_gateaway/models.py
from django.db import models

# Create your models here.

College-Corner/Cart_and_Checkout/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required

# @login_required(login_url=' /login/')
def cartcalling(request):
    return cartcalling2(request)


def cartcalling2(request):
    return render(request,'Cart.html')

College-Corner/CollegeCorner/views.py
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')

def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')    

College-Corner/Product_Catalog/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Product

class product_list(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'productlist.html'
    context_object_name = 'products'
    paginate_by = 10

College-Corner/accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from CollegeCorner.views import homepage

@login_required(login_url='login/')
def home(request):
    return homepage(request)

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is None:
            error_message = 'Invalid login credentials.'
            return render(request, 'accounts/login.html', {'error_message': error_message})
            
        else:
            login(request, user)
            return homepage(request)
            
    else:
        return render(request, 'accounts/login.html')

@login_required(login_url='login')
def logout_view(request):
    logout(request)
    return homepage(request)
    
def signup_view(request):
    if request.method == 'POST':
        # Handle signup form submission
        # Extract and save user registration data
        # You can use Django's built-in UserCreationForm or create your own form
        # Redirect to the login page after successful signup
        return homepage(request)
    else:
        return render(request, 'accounts/signup.html')

College-Corner/order_management/views.py
from django.shortcuts import render

# Create your views here.

College-Corner/payment_gateaway/views.py
from django.shortcuts import render

# Create your views here.

College-Corner/Product_Catalog/templates/Product_Catalog/productlist.html
{% extends 'base_layout.html' %}

{% block content }
<h2>Helo welcome to our product site</h2>
<button>CLICk here</button>
{% endblock %}

College-Corner/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

College-Corner/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

College-Corner/templates/Profile.html
<link rel="stylesheet" href="{% static 'styles.css' %}">

College-Corner/templates/about.html
{% extends 'base_layout.html' %}

    {% block content %}

    {% endblock %}
    

College-Corner/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="/static/styles.css"> -->
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>hello</title>
</head>
    <body>
        <div class="wrapper">
           
            <nav>
                <ul>
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                </ul>
            </nav>
            {% block content %}
            {% endblock %}  
        </div>
       

    </body>
</html>

College-Corner/templates/index.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Hello my name is navansh</h1>
{% endblock %}  

    
    

College-Corner/templates/options.html
<link rel="stylesheet" href="{% static 'styles.css' %}">

College-Corner/templates/wishlist.html
<link rel="stylesheet" href="{% static 'styles.css' %}">